name: Generate.sh

on:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - 'bin/generate.sh'

jobs:
  generate:
    name: Generate on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up JDK 11
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: temurin
          java-version: 11
          cache: 'maven'

      - name: Run generate.sh
        run: ./bin/generate.sh

      - name: Upload grpc
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        with:
          name: ${{ matrix.os }}-grpc
          path: grpc/
          if-no-files-found: error
