name: Update Config

on:
  workflow_dispatch:
jobs:
  build:
    name: Build on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false
        if: startsWith(matrix.os, 'windows')

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up JDK 11
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: temurin
          java-version: 11
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B formatter:validate verify --file pom.xml

      - name: Copy Configuration
        run: |
           rm -rf docs/config
           cp -r target/asciidoc/generated/config docs/

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            docs/config
          commit-message: 'Update configuration refernce'
          committer: GitHub <noreply@github.com>
          delete-branch: true
          title: 'Update configuration refernce'
          draft: false
